language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

before_script:
  - bash travis_setup.sh

# run tests, e.g. python setup.py test
script:
  - export DATASERV_MAX_PING="10"
  - export DATASERV_CLIENT_CONNECTION_RETRY_DELAY="1"
  - coverage run --source="dataserv_client" setup.py test

# run coverage
after_success:
  - coveralls

# post to slack
notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
